spring:
  application:
    name: open-api
  jackson:
    serialization:
      write-dates-as-timestamps: true
  redis:
    # Redis数据库索引（默认为0  172.16.1.241
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 1234567
    # 连接超时时间（毫秒）
    timeout: 2000ms
    Lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    consumer:
      enable-auto-commit: true
      #      分组是指消费者分组 共用一个偏移量
      group-id: group
      auto-offset-reset: latest
      bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
server:
  port: 6060
t3:
  swagger:
    title: OpenAPI
    desc: OpenAPI，提供包括活开放服务，无需验证身份。
    version:  0.0.1
    company: 出行服务公司
    lisense: 服务条款
    contact: 后台开发团队
    website:
dubbo:
  application:
    name: open-api
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: dubbo
    port: 20880
  consumer:
    filter: consumerLogFilter
    parameters:
      consumerLogFilter: true